### ISSUE TITLE
Does Protobuild git cache work with spaces in user names?

### ISSUE THREAD

**Issue by emarcotte** [hach-que/Protobuild#114]
I made a big mistake when I did a recent windows re-install... forgetting it would put spaces in my username. When trying to generate a project that has git references (monogame and my own packages) I get an error:

```
Resolving: https-git://github.com/mono/MonoGame
Package type not specified (and no file at MonoGame\.git), requesting binary version.
Creating and emptying MonoGame\Windows
Marking MonoGame as ignored for Git
Unable to resolve binary package for version "develop" and platform "Windows", falling back to source version
Executing: git fetch origin +refs/heads/*:refs/heads/* (in C:\Users\Eugene Marcotte\AppData\Roaming\.protobuild-cache\52877da7a79bf4a971dac7fea66c4090b288be94--source)
Executing: git clone C:\Users\Eugene Marcotte\AppData\Roaming\.protobuild-cache\52877da7a79bf4a971dac7fea66c4090b288be94--source MonoGame
System.InvalidOperationException: Got an unexpected exit code of 129 from Git
   at Protobuild.GitUtils.RunGit(String folder, String str)
   at Protobuild.SourcePackageContent.ExtractTo(String path)
   at Protobuild.PackageManager.ResolveLibrarySource(PackageRef reference, String source, Boolean forceUpgrade)
   at Protobuild.PackageManager.ResolveLibraryBinary(PackageRef reference, String platform, String source, Boolean forceUpgrade)
   at Protobuild.PackageManager.Resolve(ModuleInfo module, PackageRef reference, String platform, String templateName, Nullable`1 source, Boolean forceUpgrade)
   at Protobuild.PackageManager.ResolveAll(ModuleInfo module, String platform)
   at Protobuild.ActionDispatch.PerformAction(ModuleInfo module, String action, String platform, String[] enabledServices, String[] disabledServices, String serviceSpecPath, Boolean debugServiceResolution, Boolean disablePackageResolution)
   at Protobuild.GenerateCommand.Execute(Execution execution)
   at Protobuild.MainClass.Main(String[] args)
```

I think it is due to a lack of escaping around this area, but I'm not 100% certain: https://github.com/hach-que/Protobuild/blob/ce28ca5f6a2c113263c874c0fd8d96cca86265b1/Protobuild.Internal/Packages/PackageContent/SourcePackageContent.cs#L31 

Will probably try to debug more later (tomorrow).

**Comment by hach-que** [comment]
Bleh, I didn't even think spaces could be in the AppData path :(

But yes, it sounds like that's the issue.

**Comment by emarcotte** [comment]
Turns out I had ended up rebuilding the computer I was using this week and just fixed my username. If I make the same mistake again I'll try to work on fixing it :)

**Comment by Hurtyto** [comment]
Hey :) I have the similar problem. I moved the MonoGame-develop source code to "C:\" where there are no spaces and it still gives me the same error. Can you tell me how did you fix it?
Thanks,
George.

**Comment by Hurtyto** [comment]
C:\MonoGame>Protobuild.exe
Starting resolution of packages for Windows...
Resolving: https-git://github.com/OutOfOrder/MonoKickstart.git
Package type not specified (and no file at ThirdParty/Kickstart\.git), requesting binary version.
Creating and emptying ThirdParty/Kickstart\Windows
Marking ThirdParty/Kickstart as ignored for Git
Unable to resolve binary package for version "master" and platform "Windows", falling back to source version
WARNING: Source package cache is corrupt, removing and cloning again...
Executing: git clone --progress --bare https://github.com/OutOfOrder/MonoKickstart.git C:\Users\georg\AppData\Roaming\.protobuild-cache\ec904ab94963ff65b75666b7cb00050df02418d9--source
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Protobuild.GitUtils.RunGitInternal(String str, String workingDirectory, String consoleWriteLine)
   at Protobuild.PackageCache.GetSourcePackage(String url, String gitHash)
   at Protobuild.PackageManager.ResolveLibrarySource(PackageRef reference, String source, Boolean forceUpgrade)
   at Protobuild.PackageManager.ResolveLibraryBinary(PackageRef reference, String platform, String source, Boolean forceUpgrade)
   at Protobuild.PackageManager.Resolve(ModuleInfo module, PackageRef reference, String platform, String templateName, Nullable`1 source, Boolean forceUpgrade)
   at Protobuild.PackageManager.ResolveAll(ModuleInfo module, String platform)
   at Protobuild.ActionDispatch.PerformAction(ModuleInfo module, String action, String platform, String[] enabledServices, String[] disabledServices, String serviceSpecPath, Boolean debugServiceResolution, Boolean disablePackageResolution, Boolean disableHostPlatformGeneration)
   at Protobuild.ActionDispatch.DefaultAction(ModuleInfo module, String platform, String[] enabledServices, String[] disabledServices, String serviceSpecPath, Boolean debugServiceResolution, Boolean disablePackageResolution, Boolean disableHostPlatformGeneration)
   at Protobuild.DefaultCommand.Execute(Execution execution)
   at Protobuild.MainClass.Main(String[] args)

**Comment by hach-que** [comment]
```
C:\Users\georg\AppData\Roaming.protobuild-cache\ec904ab94963ff65b75666b7cb00050df02418d9--source
```

This line stands out to me - there's no slash between the Roaming folder and the Protobuild cache.  I'll have a look at the source code to see what is happening here.

**Comment by hach-que** [comment]
Actually, from the error it sounds like Git might not be on your PATH.  Can you verify that running "git" form a standard Windows command prompt works?

**Comment by Hurtyto** [comment]
Actually I managed to make it work. I forgot to download the dependencies. Fool on me. :)

-----Original Message-----

**Comment by hach-que** [comment]
That shouldn't be an issue; Protobuild should work in this scenario and it should download the dependencies for you.

Where is Git located on your machine?  Are you using GitHub for Windows?

**Comment by Hurtyto** [comment]
I don't use Git. I manually download the repos and extract them :)

-----Original Message-----

**Comment by hach-que** [comment]
Oh, in that case there's nothing we can do :P

**Comment by hach-que** [comment]
(Well I guess I could bundle a portable Git as a binary package on protobuild.org, and install it if no Git was found in the PATH for Windows, but I'd prefer not to do that)

**Comment by Hurtyto** [comment]
Hehe :) it's also a resolution.  When I got the dependencies installed everything went smooth :)

-----Original Message-----

**Comment by MartyMaro** [comment]
I get the same issue and I got a space in my username. Is this bug still present?

**Comment by hach-que** [comment]
Yes, we didn't have anyone to test a resolution since the original reporter fixed the issue when they reinstalled Windows.

If you now have an environment which reproduces the issue, I can work on a fix for you to test.
