### ISSUE TITLE
IOException while saving service specification

### ISSUE THREAD

**Issue by hach-que** [hach-que/Protobuild#152]
Observed this in the build logs:

```
System.IO.IOException: The file exists.
67	
68	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
69	   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
70	   at Protobuild.Services.ServiceManager.SaveServiceSpec(List`1 services)
71	   at Protobuild.Tasks.GenerateProjectsTask.Execute()
72	   at Protobuild.ActionDispatch.GenerateProjectsForPlatform(ModuleInfo module, String platform, String[] enabledServices, String[] disabledServices, String serviceSpecPath, Boolean debugServiceResolution, Boolean disablePackageResolution, Boolean disableHostPlatformGeneration, Action requiresHostPlatform)
73	   at Protobuild.ActionDispatch.ResyncProjectsForPlatform(ModuleInfo module, String platform, String[] enabledServices, String[] disabledServices, String serviceSpecPath, Boolean debugServiceResolution, Boolean disablePackageResolution, Boolean disableHostPlatformGeneration, Action requiresHostPlatform)
74	   at Protobuild.ActionDispatch.PerformAction(ModuleInfo module, String action, String platform, String[] enabledServices, String[] disabledServices, String serviceSpecPath, Boolean debugServiceResolution, Boolean disablePackageResolution, Boolean disableHostPlatformGeneration)
75	   at Protobuild.ResyncCommand.Execute(Execution execution)
76	   at Protobuild.MainClass.Main(String[] args)
```

**Comment by hach-que** [comment]
This also caused a failure in the regression tests.
