### ISSUE TITLE
Win32Exception "The process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by hach-que** [hach-que/Protobuild#99]
```
WARNING: Unknown tag 'Services' encountered.
87	Packaging: Jitter
88	WARNING: Unknown tag 'Services' encountered.
89	Packaging: Newtonsoft.Json
90	Packaging: protobuf-net
91	Writing package in tar/lzma format...
92	Deduplicating files in package...
93	Deduplicating files in package; 13% complete (67 of 481 files)
94	Deduplicating files in package; 19% complete (95 of 481 files)
95	Deduplicating files in package; 20% complete (99 of 481 files)
96	Deduplicating files in package; 21% complete (103 of 481 files)
97	Deduplicating files in package; 34% complete (165 of 481 files)
98	Deduplicating files in package; 36% complete (176 of 481 files)
99	Deduplicating files in package; 37% complete (179 of 481 files)
100	Deduplicating files in package; 37% complete (181 of 481 files)
101	Deduplicating files in package; 39% complete (188 of 481 files)
102	Deduplicating files in package; 41% complete (199 of 481 files)System.IO.IOException: The process cannot access the file 'C:\Users\build\Documents\Leases\5595\Protogame.Tests\bin\Windows\AnyCPU\Debug\Ninject.dll' because it is being used by another process.
103	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
104	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
105	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
106	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
107	   at Protobuild.Deduplicator.AddFile(DeduplicatorState state, FileInfo sourceFile, String destinationPath)
108	   at Protobuild.PackPackageCommand.Execute(Execution execution)
109	   at Protobuild.MainClass.Main(String[] args)
110	
```

**Comment by hach-que** [comment]
At the time this happened, the unit tests were running.
